### ISSUE TITLE
What if there's only a type we don't want?

### ISSUE THREAD

**Issue by bfred-it** [ben-eb/postcss-discard-font-face#3]
I tried running this module as `discardFonts(['woff'])`, which should only leave the `woff` file but… what if the CSS only has an `otf` font? Shouldn't `dff` leave it as it is a output a warning?

**Comment by ben-eb** [comment]
The array works as a whitelist, not as a blacklist. So if you want to keep `otf` and `ttf`, for example, and remove `woff`, pass `['otf', 'ttf']`.

**Comment by bfred-it** [comment]
Exactly, my question then is: what is the use case? How/when is this used?

As it is, imho it can only be used on its own to _fix_ old stylesheets, once.

If it's supposed to be an automated dev-error correction or minifier, then it can break the content without the dev noticing.

**Comment by bfred-it** [comment]
To make it clearer, here's an example:

```css
/* input */
@font-face {
    font-family: 'name';
    src: url('name.otf') format('opentype'),
         url('name.woff') format('woff');
}
@font-face {
    font-family: 'name-2';
    src: url('name2.otf') format('opentype');
}
```
```css
/* current output for ['woff'] */
@font-face {
    font-family: 'name';
    src: url('name.woff') format('woff'); /* OK */
}
@font-face {
    font-family: 'name-2';
    /* BROKEN */
}
```
```css
/* desired output for ['woff']  */
@font-face {
    font-family: 'name';
    src: url('name.woff') format('woff'); /* OK */
}
@font-face {
    font-family: 'name-2';
    src: url('name2.otf') format('opentype');
    /* WARNING: preferred type missing, src unchanged */
}
```

In short, the whitelist should be a a suggestion, not an order, as it might silently break functionality.
